/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hrms.leave.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LeaveRequest service. Represents a row in the &quot;HRMS_LeaveRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hrms.leave.model.impl.LeaveRequestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hrms.leave.model.impl.LeaveRequestImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveRequest
 * @generated
 */
@ProviderType
public interface LeaveRequestModel
	extends BaseModel<LeaveRequest>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave request model instance should use the {@link LeaveRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this leave request.
	 *
	 * @return the primary key of this leave request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave request.
	 *
	 * @param primaryKey the primary key of this leave request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this leave request.
	 *
	 * @return the uuid of this leave request
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this leave request.
	 *
	 * @param uuid the uuid of this leave request
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the leave request ID of this leave request.
	 *
	 * @return the leave request ID of this leave request
	 */
	public long getLeaveRequestId();

	/**
	 * Sets the leave request ID of this leave request.
	 *
	 * @param leaveRequestId the leave request ID of this leave request
	 */
	public void setLeaveRequestId(long leaveRequestId);

	/**
	 * Returns the group ID of this leave request.
	 *
	 * @return the group ID of this leave request
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this leave request.
	 *
	 * @param groupId the group ID of this leave request
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this leave request.
	 *
	 * @return the company ID of this leave request
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave request.
	 *
	 * @param companyId the company ID of this leave request
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this leave request.
	 *
	 * @return the user ID of this leave request
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this leave request.
	 *
	 * @param userId the user ID of this leave request
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this leave request.
	 *
	 * @return the user uuid of this leave request
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this leave request.
	 *
	 * @param userUuid the user uuid of this leave request
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this leave request.
	 *
	 * @return the user name of this leave request
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this leave request.
	 *
	 * @param userName the user name of this leave request
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the employee ID of this leave request.
	 *
	 * @return the employee ID of this leave request
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this leave request.
	 *
	 * @param employeeId the employee ID of this leave request
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the leave type of this leave request.
	 *
	 * @return the leave type of this leave request
	 */
	@AutoEscape
	public String getLeaveType();

	/**
	 * Sets the leave type of this leave request.
	 *
	 * @param leaveType the leave type of this leave request
	 */
	public void setLeaveType(String leaveType);

	/**
	 * Returns the from date of this leave request.
	 *
	 * @return the from date of this leave request
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this leave request.
	 *
	 * @param fromDate the from date of this leave request
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this leave request.
	 *
	 * @return the to date of this leave request
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this leave request.
	 *
	 * @param toDate the to date of this leave request
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the reason of this leave request.
	 *
	 * @return the reason of this leave request
	 */
	@AutoEscape
	public String getReason();

	/**
	 * Sets the reason of this leave request.
	 *
	 * @param reason the reason of this leave request
	 */
	public void setReason(String reason);

	/**
	 * Returns the status of this leave request.
	 *
	 * @return the status of this leave request
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this leave request.
	 *
	 * @param status the status of this leave request
	 */
	public void setStatus(String status);

	/**
	 * Returns the approver user ID of this leave request.
	 *
	 * @return the approver user ID of this leave request
	 */
	public long getApproverUserId();

	/**
	 * Sets the approver user ID of this leave request.
	 *
	 * @param approverUserId the approver user ID of this leave request
	 */
	public void setApproverUserId(long approverUserId);

	/**
	 * Returns the approver user uuid of this leave request.
	 *
	 * @return the approver user uuid of this leave request
	 */
	public String getApproverUserUuid();

	/**
	 * Sets the approver user uuid of this leave request.
	 *
	 * @param approverUserUuid the approver user uuid of this leave request
	 */
	public void setApproverUserUuid(String approverUserUuid);

	/**
	 * Returns the approver comments of this leave request.
	 *
	 * @return the approver comments of this leave request
	 */
	@AutoEscape
	public String getApproverComments();

	/**
	 * Sets the approver comments of this leave request.
	 *
	 * @param approverComments the approver comments of this leave request
	 */
	public void setApproverComments(String approverComments);

	/**
	 * Returns the create date of this leave request.
	 *
	 * @return the create date of this leave request
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave request.
	 *
	 * @param createDate the create date of this leave request
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this leave request.
	 *
	 * @return the modified date of this leave request
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave request.
	 *
	 * @param modifiedDate the modified date of this leave request
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public LeaveRequest cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:375612133