/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hrms.employee.model.impl;

import com.hrms.employee.model.Designation;
import com.hrms.employee.model.DesignationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Designation service. Represents a row in the &quot;HRMS_Designation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DesignationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DesignationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DesignationImpl
 * @generated
 */
public class DesignationModelImpl
	extends BaseModelImpl<Designation> implements DesignationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a designation model instance should use the <code>Designation</code> interface instead.
	 */
	public static final String TABLE_NAME = "HRMS_Designation";

	public static final Object[][] TABLE_COLUMNS = {
		{"designationId", Types.BIGINT}, {"designationCode", Types.VARCHAR},
		{"designationName", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"status", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("designationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("designationCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("designationName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table HRMS_Designation (designationId LONG not null primary key,designationCode VARCHAR(75) null,designationName VARCHAR(75) null,description VARCHAR(75) null,status VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table HRMS_Designation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY designation.designationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY HRMS_Designation.designationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DESIGNATIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DesignationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _designationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDesignationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _designationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Designation.class;
	}

	@Override
	public String getModelClassName() {
		return Designation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Designation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Designation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Designation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Designation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Designation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Designation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Designation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Designation, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Designation, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Designation, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Designation, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<Designation, Object>>();

			attributeGetterFunctions.put(
				"designationId", Designation::getDesignationId);
			attributeGetterFunctions.put(
				"designationCode", Designation::getDesignationCode);
			attributeGetterFunctions.put(
				"designationName", Designation::getDesignationName);
			attributeGetterFunctions.put(
				"description", Designation::getDescription);
			attributeGetterFunctions.put("status", Designation::getStatus);
			attributeGetterFunctions.put("groupId", Designation::getGroupId);
			attributeGetterFunctions.put(
				"companyId", Designation::getCompanyId);
			attributeGetterFunctions.put("userId", Designation::getUserId);
			attributeGetterFunctions.put("userName", Designation::getUserName);
			attributeGetterFunctions.put(
				"createDate", Designation::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Designation::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Designation, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Designation, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Designation, ?>>();

			attributeSetterBiConsumers.put(
				"designationId",
				(BiConsumer<Designation, Long>)Designation::setDesignationId);
			attributeSetterBiConsumers.put(
				"designationCode",
				(BiConsumer<Designation, String>)
					Designation::setDesignationCode);
			attributeSetterBiConsumers.put(
				"designationName",
				(BiConsumer<Designation, String>)
					Designation::setDesignationName);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<Designation, String>)Designation::setDescription);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<Designation, String>)Designation::setStatus);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<Designation, Long>)Designation::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Designation, Long>)Designation::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<Designation, Long>)Designation::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Designation, String>)Designation::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Designation, Date>)Designation::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Designation, Date>)Designation::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getDesignationId() {
		return _designationId;
	}

	@Override
	public void setDesignationId(long designationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_designationId = designationId;
	}

	@Override
	public String getDesignationCode() {
		if (_designationCode == null) {
			return "";
		}
		else {
			return _designationCode;
		}
	}

	@Override
	public void setDesignationCode(String designationCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_designationCode = designationCode;
	}

	@Override
	public String getDesignationName() {
		if (_designationName == null) {
			return "";
		}
		else {
			return _designationName;
		}
	}

	@Override
	public void setDesignationName(String designationName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_designationName = designationName;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Designation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Designation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Designation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DesignationImpl designationImpl = new DesignationImpl();

		designationImpl.setDesignationId(getDesignationId());
		designationImpl.setDesignationCode(getDesignationCode());
		designationImpl.setDesignationName(getDesignationName());
		designationImpl.setDescription(getDescription());
		designationImpl.setStatus(getStatus());
		designationImpl.setGroupId(getGroupId());
		designationImpl.setCompanyId(getCompanyId());
		designationImpl.setUserId(getUserId());
		designationImpl.setUserName(getUserName());
		designationImpl.setCreateDate(getCreateDate());
		designationImpl.setModifiedDate(getModifiedDate());

		designationImpl.resetOriginalValues();

		return designationImpl;
	}

	@Override
	public Designation cloneWithOriginalValues() {
		DesignationImpl designationImpl = new DesignationImpl();

		designationImpl.setDesignationId(
			this.<Long>getColumnOriginalValue("designationId"));
		designationImpl.setDesignationCode(
			this.<String>getColumnOriginalValue("designationCode"));
		designationImpl.setDesignationName(
			this.<String>getColumnOriginalValue("designationName"));
		designationImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		designationImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));
		designationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		designationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		designationImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		designationImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		designationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		designationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return designationImpl;
	}

	@Override
	public int compareTo(Designation designation) {
		long primaryKey = designation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Designation)) {
			return false;
		}

		Designation designation = (Designation)object;

		long primaryKey = designation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Designation> toCacheModel() {
		DesignationCacheModel designationCacheModel =
			new DesignationCacheModel();

		designationCacheModel.designationId = getDesignationId();

		designationCacheModel.designationCode = getDesignationCode();

		String designationCode = designationCacheModel.designationCode;

		if ((designationCode != null) && (designationCode.length() == 0)) {
			designationCacheModel.designationCode = null;
		}

		designationCacheModel.designationName = getDesignationName();

		String designationName = designationCacheModel.designationName;

		if ((designationName != null) && (designationName.length() == 0)) {
			designationCacheModel.designationName = null;
		}

		designationCacheModel.description = getDescription();

		String description = designationCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			designationCacheModel.description = null;
		}

		designationCacheModel.status = getStatus();

		String status = designationCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			designationCacheModel.status = null;
		}

		designationCacheModel.groupId = getGroupId();

		designationCacheModel.companyId = getCompanyId();

		designationCacheModel.userId = getUserId();

		designationCacheModel.userName = getUserName();

		String userName = designationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			designationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			designationCacheModel.createDate = createDate.getTime();
		}
		else {
			designationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			designationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			designationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return designationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Designation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Designation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Designation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Designation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Designation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Designation.class, ModelWrapper.class);

	}

	private long _designationId;
	private String _designationCode;
	private String _designationName;
	private String _description;
	private String _status;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<Designation, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Designation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("designationId", _designationId);
		_columnOriginalValues.put("designationCode", _designationCode);
		_columnOriginalValues.put("designationName", _designationName);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("designationId", 1L);

		columnBitmasks.put("designationCode", 2L);

		columnBitmasks.put("designationName", 4L);

		columnBitmasks.put("description", 8L);

		columnBitmasks.put("status", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Designation _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-603040030