/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hrms.employee.model.impl;

import com.hrms.employee.model.Designation;
import com.hrms.employee.service.DesignationLocalServiceUtil;

/**
 * The extended model base implementation for the Designation service. Represents a row in the &quot;HRMS_Designation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DesignationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DesignationImpl
 * @see Designation
 * @generated
 */
public abstract class DesignationBaseImpl
	extends DesignationModelImpl implements Designation {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a designation model instance should use the <code>Designation</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DesignationLocalServiceUtil.addDesignation(this);
		}
		else {
			DesignationLocalServiceUtil.updateDesignation(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:39348453