/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hrms.employee.model.impl;

import com.hrms.employee.model.Employee;
import com.hrms.employee.model.EmployeeModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Employee service. Represents a row in the &quot;HRMS_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeImpl
 * @generated
 */
public class EmployeeModelImpl
	extends BaseModelImpl<Employee> implements EmployeeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee model instance should use the <code>Employee</code> interface instead.
	 */
	public static final String TABLE_NAME = "HRMS_Employee";

	public static final Object[][] TABLE_COLUMNS = {
		{"employeeId", Types.BIGINT}, {"employeeCode", Types.VARCHAR},
		{"firstName", Types.VARCHAR}, {"lastName", Types.VARCHAR},
		{"email", Types.VARCHAR}, {"phoneNumber", Types.VARCHAR},
		{"department", Types.VARCHAR}, {"designation", Types.VARCHAR},
		{"joiningDate", Types.TIMESTAMP}, {"status", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("phoneNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("department", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("designation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("joiningDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table HRMS_Employee (employeeId LONG not null primary key,employeeCode VARCHAR(75) null,firstName VARCHAR(75) null,lastName VARCHAR(75) null,email VARCHAR(75) null,phoneNumber VARCHAR(75) null,department VARCHAR(75) null,designation VARCHAR(75) null,joiningDate DATE null,status VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table HRMS_Employee";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employee.employeeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY HRMS_Employee.employeeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.hrms.employee.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.hrms.employee.model.Employee"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.hrms.employee.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.hrms.employee.model.Employee"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.hrms.employee.service.util.ServiceProps.get(
			"lock.expiration.time.com.hrms.employee.model.Employee"));

	public EmployeeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Employee.class;
	}

	@Override
	public String getModelClassName() {
		return Employee.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Employee, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Employee, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Employee, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Employee)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Employee, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Employee, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Employee)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Employee, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Employee, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Employee>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Employee.class.getClassLoader(), Employee.class,
			ModelWrapper.class);

		try {
			Constructor<Employee> constructor =
				(Constructor<Employee>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Employee, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<Employee, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Employee, Object>>();

		attributeGetterFunctions.put(
			"employeeId",
			new Function<Employee, Object>() {

				@Override
				public Object apply(Employee employee) {
					return employee.getEmployeeId();
				}

			});
		attributeGetterFunctions.put(
			"employeeCode",
			new Function<Employee, Object>() {

				@Override
				public Object apply(Employee employee) {
					return employee.getEmployeeCode();
				}

			});
		attributeGetterFunctions.put(
			"firstName",
			new Function<Employee, Object>() {

				@Override
				public Object apply(Employee employee) {
					return employee.getFirstName();
				}

			});
		attributeGetterFunctions.put(
			"lastName",
			new Function<Employee, Object>() {

				@Override
				public Object apply(Employee employee) {
					return employee.getLastName();
				}

			});
		attributeGetterFunctions.put(
			"email",
			new Function<Employee, Object>() {

				@Override
				public Object apply(Employee employee) {
					return employee.getEmail();
				}

			});
		attributeGetterFunctions.put(
			"phoneNumber",
			new Function<Employee, Object>() {

				@Override
				public Object apply(Employee employee) {
					return employee.getPhoneNumber();
				}

			});
		attributeGetterFunctions.put(
			"department",
			new Function<Employee, Object>() {

				@Override
				public Object apply(Employee employee) {
					return employee.getDepartment();
				}

			});
		attributeGetterFunctions.put(
			"designation",
			new Function<Employee, Object>() {

				@Override
				public Object apply(Employee employee) {
					return employee.getDesignation();
				}

			});
		attributeGetterFunctions.put(
			"joiningDate",
			new Function<Employee, Object>() {

				@Override
				public Object apply(Employee employee) {
					return employee.getJoiningDate();
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<Employee, Object>() {

				@Override
				public Object apply(Employee employee) {
					return employee.getStatus();
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<Employee, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<Employee, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Employee, ?>>();

		attributeSetterBiConsumers.put(
			"employeeId",
			new BiConsumer<Employee, Object>() {

				@Override
				public void accept(Employee employee, Object employeeIdObject) {
					employee.setEmployeeId((Long)employeeIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"employeeCode",
			new BiConsumer<Employee, Object>() {

				@Override
				public void accept(
					Employee employee, Object employeeCodeObject) {

					employee.setEmployeeCode((String)employeeCodeObject);
				}

			});
		attributeSetterBiConsumers.put(
			"firstName",
			new BiConsumer<Employee, Object>() {

				@Override
				public void accept(Employee employee, Object firstNameObject) {
					employee.setFirstName((String)firstNameObject);
				}

			});
		attributeSetterBiConsumers.put(
			"lastName",
			new BiConsumer<Employee, Object>() {

				@Override
				public void accept(Employee employee, Object lastNameObject) {
					employee.setLastName((String)lastNameObject);
				}

			});
		attributeSetterBiConsumers.put(
			"email",
			new BiConsumer<Employee, Object>() {

				@Override
				public void accept(Employee employee, Object emailObject) {
					employee.setEmail((String)emailObject);
				}

			});
		attributeSetterBiConsumers.put(
			"phoneNumber",
			new BiConsumer<Employee, Object>() {

				@Override
				public void accept(
					Employee employee, Object phoneNumberObject) {

					employee.setPhoneNumber((String)phoneNumberObject);
				}

			});
		attributeSetterBiConsumers.put(
			"department",
			new BiConsumer<Employee, Object>() {

				@Override
				public void accept(Employee employee, Object departmentObject) {
					employee.setDepartment((String)departmentObject);
				}

			});
		attributeSetterBiConsumers.put(
			"designation",
			new BiConsumer<Employee, Object>() {

				@Override
				public void accept(
					Employee employee, Object designationObject) {

					employee.setDesignation((String)designationObject);
				}

			});
		attributeSetterBiConsumers.put(
			"joiningDate",
			new BiConsumer<Employee, Object>() {

				@Override
				public void accept(
					Employee employee, Object joiningDateObject) {

					employee.setJoiningDate((Date)joiningDateObject);
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<Employee, Object>() {

				@Override
				public void accept(Employee employee, Object statusObject) {
					employee.setStatus((String)statusObject);
				}

			});

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		_employeeId = employeeId;
	}

	@Override
	public String getEmployeeCode() {
		if (_employeeCode == null) {
			return "";
		}
		else {
			return _employeeCode;
		}
	}

	@Override
	public void setEmployeeCode(String employeeCode) {
		_employeeCode = employeeCode;
	}

	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		_firstName = firstName;
	}

	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		_lastName = lastName;
	}

	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@Override
	public String getPhoneNumber() {
		if (_phoneNumber == null) {
			return "";
		}
		else {
			return _phoneNumber;
		}
	}

	@Override
	public void setPhoneNumber(String phoneNumber) {
		_phoneNumber = phoneNumber;
	}

	@Override
	public String getDepartment() {
		if (_department == null) {
			return "";
		}
		else {
			return _department;
		}
	}

	@Override
	public void setDepartment(String department) {
		_department = department;
	}

	@Override
	public String getDesignation() {
		if (_designation == null) {
			return "";
		}
		else {
			return _designation;
		}
	}

	@Override
	public void setDesignation(String designation) {
		_designation = designation;
	}

	@Override
	public Date getJoiningDate() {
		return _joiningDate;
	}

	@Override
	public void setJoiningDate(Date joiningDate) {
		_joiningDate = joiningDate;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Employee.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Employee toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Employee>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeImpl employeeImpl = new EmployeeImpl();

		employeeImpl.setEmployeeId(getEmployeeId());
		employeeImpl.setEmployeeCode(getEmployeeCode());
		employeeImpl.setFirstName(getFirstName());
		employeeImpl.setLastName(getLastName());
		employeeImpl.setEmail(getEmail());
		employeeImpl.setPhoneNumber(getPhoneNumber());
		employeeImpl.setDepartment(getDepartment());
		employeeImpl.setDesignation(getDesignation());
		employeeImpl.setJoiningDate(getJoiningDate());
		employeeImpl.setStatus(getStatus());

		employeeImpl.resetOriginalValues();

		return employeeImpl;
	}

	@Override
	public int compareTo(Employee employee) {
		long primaryKey = employee.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Employee)) {
			return false;
		}

		Employee employee = (Employee)object;

		long primaryKey = employee.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Employee> toCacheModel() {
		EmployeeCacheModel employeeCacheModel = new EmployeeCacheModel();

		employeeCacheModel.employeeId = getEmployeeId();

		employeeCacheModel.employeeCode = getEmployeeCode();

		String employeeCode = employeeCacheModel.employeeCode;

		if ((employeeCode != null) && (employeeCode.length() == 0)) {
			employeeCacheModel.employeeCode = null;
		}

		employeeCacheModel.firstName = getFirstName();

		String firstName = employeeCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			employeeCacheModel.firstName = null;
		}

		employeeCacheModel.lastName = getLastName();

		String lastName = employeeCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			employeeCacheModel.lastName = null;
		}

		employeeCacheModel.email = getEmail();

		String email = employeeCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			employeeCacheModel.email = null;
		}

		employeeCacheModel.phoneNumber = getPhoneNumber();

		String phoneNumber = employeeCacheModel.phoneNumber;

		if ((phoneNumber != null) && (phoneNumber.length() == 0)) {
			employeeCacheModel.phoneNumber = null;
		}

		employeeCacheModel.department = getDepartment();

		String department = employeeCacheModel.department;

		if ((department != null) && (department.length() == 0)) {
			employeeCacheModel.department = null;
		}

		employeeCacheModel.designation = getDesignation();

		String designation = employeeCacheModel.designation;

		if ((designation != null) && (designation.length() == 0)) {
			employeeCacheModel.designation = null;
		}

		Date joiningDate = getJoiningDate();

		if (joiningDate != null) {
			employeeCacheModel.joiningDate = joiningDate.getTime();
		}
		else {
			employeeCacheModel.joiningDate = Long.MIN_VALUE;
		}

		employeeCacheModel.status = getStatus();

		String status = employeeCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			employeeCacheModel.status = null;
		}

		return employeeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Employee, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Employee, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Employee, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Employee)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Employee, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Employee, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Employee, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Employee)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Employee>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _employeeId;
	private String _employeeCode;
	private String _firstName;
	private String _lastName;
	private String _email;
	private String _phoneNumber;
	private String _department;
	private String _designation;
	private Date _joiningDate;
	private String _status;
	private Employee _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:5388025