/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hrms.leave.model.impl;

import com.hrms.leave.model.LeaveRequest;
import com.hrms.leave.service.LeaveRequestLocalServiceUtil;

/**
 * The extended model base implementation for the LeaveRequest service. Represents a row in the &quot;HRMS_LeaveRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveRequestImpl
 * @see LeaveRequest
 * @generated
 */
public abstract class LeaveRequestBaseImpl
	extends LeaveRequestModelImpl implements LeaveRequest {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave request model instance should use the <code>LeaveRequest</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LeaveRequestLocalServiceUtil.addLeaveRequest(this);
		}
		else {
			LeaveRequestLocalServiceUtil.updateLeaveRequest(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1664582207