/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hrms.leave.model.impl;

import com.hrms.leave.model.LeaveRequest;
import com.hrms.leave.model.LeaveRequestModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LeaveRequest service. Represents a row in the &quot;HRMS_LeaveRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LeaveRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveRequestImpl
 * @generated
 */
public class LeaveRequestModelImpl
	extends BaseModelImpl<LeaveRequest> implements LeaveRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave request model instance should use the <code>LeaveRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "HRMS_LeaveRequest";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"leaveRequestId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"employeeId", Types.BIGINT}, {"leaveType", Types.VARCHAR},
		{"fromDate", Types.TIMESTAMP}, {"toDate", Types.TIMESTAMP},
		{"reason", Types.VARCHAR}, {"status", Types.VARCHAR},
		{"approverUserId", Types.BIGINT}, {"approverComments", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leaveRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leaveType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fromDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("toDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("reason", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("approverUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("approverComments", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table HRMS_LeaveRequest (uuid_ VARCHAR(75) null,leaveRequestId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,employeeId LONG,leaveType VARCHAR(75) null,fromDate DATE null,toDate DATE null,reason VARCHAR(75) null,status VARCHAR(75) null,approverUserId LONG,approverComments VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table HRMS_LeaveRequest";

	public static final String ORDER_BY_JPQL =
		" ORDER BY leaveRequest.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY HRMS_LeaveRequest.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LeaveRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveRequestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveRequestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveRequest.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LeaveRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LeaveRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LeaveRequest)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LeaveRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LeaveRequest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LeaveRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LeaveRequest, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LeaveRequest, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<LeaveRequest, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<LeaveRequest, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<LeaveRequest, Object>>();

			attributeGetterFunctions.put("uuid", LeaveRequest::getUuid);
			attributeGetterFunctions.put(
				"leaveRequestId", LeaveRequest::getLeaveRequestId);
			attributeGetterFunctions.put("groupId", LeaveRequest::getGroupId);
			attributeGetterFunctions.put(
				"companyId", LeaveRequest::getCompanyId);
			attributeGetterFunctions.put("userId", LeaveRequest::getUserId);
			attributeGetterFunctions.put("userName", LeaveRequest::getUserName);
			attributeGetterFunctions.put(
				"employeeId", LeaveRequest::getEmployeeId);
			attributeGetterFunctions.put(
				"leaveType", LeaveRequest::getLeaveType);
			attributeGetterFunctions.put("fromDate", LeaveRequest::getFromDate);
			attributeGetterFunctions.put("toDate", LeaveRequest::getToDate);
			attributeGetterFunctions.put("reason", LeaveRequest::getReason);
			attributeGetterFunctions.put("status", LeaveRequest::getStatus);
			attributeGetterFunctions.put(
				"approverUserId", LeaveRequest::getApproverUserId);
			attributeGetterFunctions.put(
				"approverComments", LeaveRequest::getApproverComments);
			attributeGetterFunctions.put(
				"createDate", LeaveRequest::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", LeaveRequest::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<LeaveRequest, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<LeaveRequest, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<LeaveRequest, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<LeaveRequest, String>)LeaveRequest::setUuid);
			attributeSetterBiConsumers.put(
				"leaveRequestId",
				(BiConsumer<LeaveRequest, Long>)
					LeaveRequest::setLeaveRequestId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<LeaveRequest, Long>)LeaveRequest::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<LeaveRequest, Long>)LeaveRequest::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<LeaveRequest, Long>)LeaveRequest::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<LeaveRequest, String>)LeaveRequest::setUserName);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<LeaveRequest, Long>)LeaveRequest::setEmployeeId);
			attributeSetterBiConsumers.put(
				"leaveType",
				(BiConsumer<LeaveRequest, String>)LeaveRequest::setLeaveType);
			attributeSetterBiConsumers.put(
				"fromDate",
				(BiConsumer<LeaveRequest, Date>)LeaveRequest::setFromDate);
			attributeSetterBiConsumers.put(
				"toDate",
				(BiConsumer<LeaveRequest, Date>)LeaveRequest::setToDate);
			attributeSetterBiConsumers.put(
				"reason",
				(BiConsumer<LeaveRequest, String>)LeaveRequest::setReason);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<LeaveRequest, String>)LeaveRequest::setStatus);
			attributeSetterBiConsumers.put(
				"approverUserId",
				(BiConsumer<LeaveRequest, Long>)
					LeaveRequest::setApproverUserId);
			attributeSetterBiConsumers.put(
				"approverComments",
				(BiConsumer<LeaveRequest, String>)
					LeaveRequest::setApproverComments);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<LeaveRequest, Date>)LeaveRequest::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<LeaveRequest, Date>)LeaveRequest::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getLeaveRequestId() {
		return _leaveRequestId;
	}

	@Override
	public void setLeaveRequestId(long leaveRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveRequestId = leaveRequestId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@Override
	public String getLeaveType() {
		if (_leaveType == null) {
			return "";
		}
		else {
			return _leaveType;
		}
	}

	@Override
	public void setLeaveType(String leaveType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_leaveType = leaveType;
	}

	@Override
	public Date getFromDate() {
		return _fromDate;
	}

	@Override
	public void setFromDate(Date fromDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fromDate = fromDate;
	}

	@Override
	public Date getToDate() {
		return _toDate;
	}

	@Override
	public void setToDate(Date toDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_toDate = toDate;
	}

	@Override
	public String getReason() {
		if (_reason == null) {
			return "";
		}
		else {
			return _reason;
		}
	}

	@Override
	public void setReason(String reason) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reason = reason;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatus() {
		return getColumnOriginalValue("status");
	}

	@Override
	public long getApproverUserId() {
		return _approverUserId;
	}

	@Override
	public void setApproverUserId(long approverUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_approverUserId = approverUserId;
	}

	@Override
	public String getApproverUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getApproverUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setApproverUserUuid(String approverUserUuid) {
	}

	@Override
	public String getApproverComments() {
		if (_approverComments == null) {
			return "";
		}
		else {
			return _approverComments;
		}
	}

	@Override
	public void setApproverComments(String approverComments) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_approverComments = approverComments;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LeaveRequest.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LeaveRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LeaveRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LeaveRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveRequestImpl leaveRequestImpl = new LeaveRequestImpl();

		leaveRequestImpl.setUuid(getUuid());
		leaveRequestImpl.setLeaveRequestId(getLeaveRequestId());
		leaveRequestImpl.setGroupId(getGroupId());
		leaveRequestImpl.setCompanyId(getCompanyId());
		leaveRequestImpl.setUserId(getUserId());
		leaveRequestImpl.setUserName(getUserName());
		leaveRequestImpl.setEmployeeId(getEmployeeId());
		leaveRequestImpl.setLeaveType(getLeaveType());
		leaveRequestImpl.setFromDate(getFromDate());
		leaveRequestImpl.setToDate(getToDate());
		leaveRequestImpl.setReason(getReason());
		leaveRequestImpl.setStatus(getStatus());
		leaveRequestImpl.setApproverUserId(getApproverUserId());
		leaveRequestImpl.setApproverComments(getApproverComments());
		leaveRequestImpl.setCreateDate(getCreateDate());
		leaveRequestImpl.setModifiedDate(getModifiedDate());

		leaveRequestImpl.resetOriginalValues();

		return leaveRequestImpl;
	}

	@Override
	public LeaveRequest cloneWithOriginalValues() {
		LeaveRequestImpl leaveRequestImpl = new LeaveRequestImpl();

		leaveRequestImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		leaveRequestImpl.setLeaveRequestId(
			this.<Long>getColumnOriginalValue("leaveRequestId"));
		leaveRequestImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		leaveRequestImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		leaveRequestImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		leaveRequestImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		leaveRequestImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		leaveRequestImpl.setLeaveType(
			this.<String>getColumnOriginalValue("leaveType"));
		leaveRequestImpl.setFromDate(
			this.<Date>getColumnOriginalValue("fromDate"));
		leaveRequestImpl.setToDate(this.<Date>getColumnOriginalValue("toDate"));
		leaveRequestImpl.setReason(
			this.<String>getColumnOriginalValue("reason"));
		leaveRequestImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));
		leaveRequestImpl.setApproverUserId(
			this.<Long>getColumnOriginalValue("approverUserId"));
		leaveRequestImpl.setApproverComments(
			this.<String>getColumnOriginalValue("approverComments"));
		leaveRequestImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		leaveRequestImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return leaveRequestImpl;
	}

	@Override
	public int compareTo(LeaveRequest leaveRequest) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), leaveRequest.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LeaveRequest)) {
			return false;
		}

		LeaveRequest leaveRequest = (LeaveRequest)object;

		long primaryKey = leaveRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveRequest> toCacheModel() {
		LeaveRequestCacheModel leaveRequestCacheModel =
			new LeaveRequestCacheModel();

		leaveRequestCacheModel.uuid = getUuid();

		String uuid = leaveRequestCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			leaveRequestCacheModel.uuid = null;
		}

		leaveRequestCacheModel.leaveRequestId = getLeaveRequestId();

		leaveRequestCacheModel.groupId = getGroupId();

		leaveRequestCacheModel.companyId = getCompanyId();

		leaveRequestCacheModel.userId = getUserId();

		leaveRequestCacheModel.userName = getUserName();

		String userName = leaveRequestCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			leaveRequestCacheModel.userName = null;
		}

		leaveRequestCacheModel.employeeId = getEmployeeId();

		leaveRequestCacheModel.leaveType = getLeaveType();

		String leaveType = leaveRequestCacheModel.leaveType;

		if ((leaveType != null) && (leaveType.length() == 0)) {
			leaveRequestCacheModel.leaveType = null;
		}

		Date fromDate = getFromDate();

		if (fromDate != null) {
			leaveRequestCacheModel.fromDate = fromDate.getTime();
		}
		else {
			leaveRequestCacheModel.fromDate = Long.MIN_VALUE;
		}

		Date toDate = getToDate();

		if (toDate != null) {
			leaveRequestCacheModel.toDate = toDate.getTime();
		}
		else {
			leaveRequestCacheModel.toDate = Long.MIN_VALUE;
		}

		leaveRequestCacheModel.reason = getReason();

		String reason = leaveRequestCacheModel.reason;

		if ((reason != null) && (reason.length() == 0)) {
			leaveRequestCacheModel.reason = null;
		}

		leaveRequestCacheModel.status = getStatus();

		String status = leaveRequestCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			leaveRequestCacheModel.status = null;
		}

		leaveRequestCacheModel.approverUserId = getApproverUserId();

		leaveRequestCacheModel.approverComments = getApproverComments();

		String approverComments = leaveRequestCacheModel.approverComments;

		if ((approverComments != null) && (approverComments.length() == 0)) {
			leaveRequestCacheModel.approverComments = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveRequestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leaveRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return leaveRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LeaveRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LeaveRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LeaveRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((LeaveRequest)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LeaveRequest>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LeaveRequest.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _leaveRequestId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private long _employeeId;
	private String _leaveType;
	private Date _fromDate;
	private Date _toDate;
	private String _reason;
	private String _status;
	private long _approverUserId;
	private String _approverComments;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LeaveRequest, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LeaveRequest)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("leaveRequestId", _leaveRequestId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("leaveType", _leaveType);
		_columnOriginalValues.put("fromDate", _fromDate);
		_columnOriginalValues.put("toDate", _toDate);
		_columnOriginalValues.put("reason", _reason);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("approverUserId", _approverUserId);
		_columnOriginalValues.put("approverComments", _approverComments);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("leaveRequestId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("employeeId", 64L);

		columnBitmasks.put("leaveType", 128L);

		columnBitmasks.put("fromDate", 256L);

		columnBitmasks.put("toDate", 512L);

		columnBitmasks.put("reason", 1024L);

		columnBitmasks.put("status", 2048L);

		columnBitmasks.put("approverUserId", 4096L);

		columnBitmasks.put("approverComments", 8192L);

		columnBitmasks.put("createDate", 16384L);

		columnBitmasks.put("modifiedDate", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LeaveRequest _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-1178396235