dependencies {
	api project(":modules:employee-service:employee-service-api")

	compileOnly group: "com.liferay.portal", name: "release.dxp.api"
}

buildService {
	apiDir = "../employee-service-api/src/main/java"
	testDir = "../employee-service-test/src/testIntegration/java"
}

group = "com.hrms.employee"