/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ai.assistance.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DocumentChunk service. Represents a row in the &quot;AI_DocumentChunk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ai.assistance.service.model.impl.DocumentChunkModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ai.assistance.service.model.impl.DocumentChunkImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DocumentChunk
 * @generated
 */
@ProviderType
public interface DocumentChunkModel extends BaseModel<DocumentChunk> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document chunk model instance should use the {@link DocumentChunk} interface instead.
	 */

	/**
	 * Returns the primary key of this document chunk.
	 *
	 * @return the primary key of this document chunk
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document chunk.
	 *
	 * @param primaryKey the primary key of this document chunk
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the chunk ID of this document chunk.
	 *
	 * @return the chunk ID of this document chunk
	 */
	public long getChunkId();

	/**
	 * Sets the chunk ID of this document chunk.
	 *
	 * @param chunkId the chunk ID of this document chunk
	 */
	public void setChunkId(long chunkId);

	/**
	 * Returns the document ID of this document chunk.
	 *
	 * @return the document ID of this document chunk
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this document chunk.
	 *
	 * @param documentId the document ID of this document chunk
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the chunk text of this document chunk.
	 *
	 * @return the chunk text of this document chunk
	 */
	@AutoEscape
	public String getChunkText();

	/**
	 * Sets the chunk text of this document chunk.
	 *
	 * @param chunkText the chunk text of this document chunk
	 */
	public void setChunkText(String chunkText);

	/**
	 * Returns the page number of this document chunk.
	 *
	 * @return the page number of this document chunk
	 */
	public int getPageNumber();

	/**
	 * Sets the page number of this document chunk.
	 *
	 * @param pageNumber the page number of this document chunk
	 */
	public void setPageNumber(int pageNumber);

	/**
	 * Returns the embedding of this document chunk.
	 *
	 * @return the embedding of this document chunk
	 */
	@AutoEscape
	public String getEmbedding();

	/**
	 * Sets the embedding of this document chunk.
	 *
	 * @param embedding the embedding of this document chunk
	 */
	public void setEmbedding(String embedding);

	@Override
	public DocumentChunk cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:342692657