/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hrms.attendance.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Attendance service. Represents a row in the &quot;HRMS_Attendance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hrms.attendance.model.impl.AttendanceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hrms.attendance.model.impl.AttendanceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Attendance
 * @generated
 */
@ProviderType
public interface AttendanceModel extends BaseModel<Attendance>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a attendance model instance should use the {@link Attendance} interface instead.
	 */

	/**
	 * Returns the primary key of this attendance.
	 *
	 * @return the primary key of this attendance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this attendance.
	 *
	 * @param primaryKey the primary key of this attendance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the attendance ID of this attendance.
	 *
	 * @return the attendance ID of this attendance
	 */
	public long getAttendanceId();

	/**
	 * Sets the attendance ID of this attendance.
	 *
	 * @param attendanceId the attendance ID of this attendance
	 */
	public void setAttendanceId(long attendanceId);

	/**
	 * Returns the group ID of this attendance.
	 *
	 * @return the group ID of this attendance
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this attendance.
	 *
	 * @param groupId the group ID of this attendance
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this attendance.
	 *
	 * @return the company ID of this attendance
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this attendance.
	 *
	 * @param companyId the company ID of this attendance
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this attendance.
	 *
	 * @return the user ID of this attendance
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this attendance.
	 *
	 * @param userId the user ID of this attendance
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this attendance.
	 *
	 * @return the user uuid of this attendance
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this attendance.
	 *
	 * @param userUuid the user uuid of this attendance
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this attendance.
	 *
	 * @return the create date of this attendance
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this attendance.
	 *
	 * @param createDate the create date of this attendance
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this attendance.
	 *
	 * @return the modified date of this attendance
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this attendance.
	 *
	 * @param modifiedDate the modified date of this attendance
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the employee ID of this attendance.
	 *
	 * @return the employee ID of this attendance
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this attendance.
	 *
	 * @param employeeId the employee ID of this attendance
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the attendance date of this attendance.
	 *
	 * @return the attendance date of this attendance
	 */
	public Date getAttendanceDate();

	/**
	 * Sets the attendance date of this attendance.
	 *
	 * @param attendanceDate the attendance date of this attendance
	 */
	public void setAttendanceDate(Date attendanceDate);

	/**
	 * Returns the check in time of this attendance.
	 *
	 * @return the check in time of this attendance
	 */
	public Date getCheckInTime();

	/**
	 * Sets the check in time of this attendance.
	 *
	 * @param checkInTime the check in time of this attendance
	 */
	public void setCheckInTime(Date checkInTime);

	/**
	 * Returns the check out time of this attendance.
	 *
	 * @return the check out time of this attendance
	 */
	public Date getCheckOutTime();

	/**
	 * Sets the check out time of this attendance.
	 *
	 * @param checkOutTime the check out time of this attendance
	 */
	public void setCheckOutTime(Date checkOutTime);

	/**
	 * Returns the check in ip of this attendance.
	 *
	 * @return the check in ip of this attendance
	 */
	@AutoEscape
	public String getCheckInIP();

	/**
	 * Sets the check in ip of this attendance.
	 *
	 * @param checkInIP the check in ip of this attendance
	 */
	public void setCheckInIP(String checkInIP);

	/**
	 * Returns the check out ip of this attendance.
	 *
	 * @return the check out ip of this attendance
	 */
	@AutoEscape
	public String getCheckOutIP();

	/**
	 * Sets the check out ip of this attendance.
	 *
	 * @param checkOutIP the check out ip of this attendance
	 */
	public void setCheckOutIP(String checkOutIP);

	/**
	 * Returns the check in latitude of this attendance.
	 *
	 * @return the check in latitude of this attendance
	 */
	public double getCheckInLatitude();

	/**
	 * Sets the check in latitude of this attendance.
	 *
	 * @param checkInLatitude the check in latitude of this attendance
	 */
	public void setCheckInLatitude(double checkInLatitude);

	/**
	 * Returns the check in longitude of this attendance.
	 *
	 * @return the check in longitude of this attendance
	 */
	public double getCheckInLongitude();

	/**
	 * Sets the check in longitude of this attendance.
	 *
	 * @param checkInLongitude the check in longitude of this attendance
	 */
	public void setCheckInLongitude(double checkInLongitude);

	/**
	 * Returns the check out latitude of this attendance.
	 *
	 * @return the check out latitude of this attendance
	 */
	public double getCheckOutLatitude();

	/**
	 * Sets the check out latitude of this attendance.
	 *
	 * @param checkOutLatitude the check out latitude of this attendance
	 */
	public void setCheckOutLatitude(double checkOutLatitude);

	/**
	 * Returns the check out longitude of this attendance.
	 *
	 * @return the check out longitude of this attendance
	 */
	public double getCheckOutLongitude();

	/**
	 * Sets the check out longitude of this attendance.
	 *
	 * @param checkOutLongitude the check out longitude of this attendance
	 */
	public void setCheckOutLongitude(double checkOutLongitude);

	/**
	 * Returns the status of this attendance.
	 *
	 * @return the status of this attendance
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this attendance.
	 *
	 * @param status the status of this attendance
	 */
	public void setStatus(String status);

	@Override
	public Attendance cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1657421720