/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ai.assistance.service.model.impl;

import ai.assistance.service.model.DocumentChunk;
import ai.assistance.service.model.DocumentChunkModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DocumentChunk service. Represents a row in the &quot;AI_DocumentChunk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DocumentChunkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DocumentChunkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DocumentChunkImpl
 * @generated
 */
public class DocumentChunkModelImpl
	extends BaseModelImpl<DocumentChunk> implements DocumentChunkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a document chunk model instance should use the <code>DocumentChunk</code> interface instead.
	 */
	public static final String TABLE_NAME = "AI_DocumentChunk";

	public static final Object[][] TABLE_COLUMNS = {
		{"chunkId", Types.BIGINT}, {"documentId", Types.BIGINT},
		{"chunkText", Types.VARCHAR}, {"pageNumber", Types.INTEGER},
		{"embedding", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("chunkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("documentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("chunkText", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("pageNumber", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("embedding", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AI_DocumentChunk (chunkId LONG not null primary key,documentId LONG,chunkText VARCHAR(75) null,pageNumber INTEGER,embedding VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table AI_DocumentChunk";

	public static final String ORDER_BY_JPQL =
		" ORDER BY documentChunk.chunkId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AI_DocumentChunk.chunkId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHUNKID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DocumentChunkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _chunkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setChunkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _chunkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DocumentChunk.class;
	}

	@Override
	public String getModelClassName() {
		return DocumentChunk.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DocumentChunk, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DocumentChunk, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DocumentChunk, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DocumentChunk)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DocumentChunk, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DocumentChunk, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DocumentChunk)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DocumentChunk, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DocumentChunk, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<DocumentChunk, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<DocumentChunk, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<DocumentChunk, Object>>();

			attributeGetterFunctions.put("chunkId", DocumentChunk::getChunkId);
			attributeGetterFunctions.put(
				"documentId", DocumentChunk::getDocumentId);
			attributeGetterFunctions.put(
				"chunkText", DocumentChunk::getChunkText);
			attributeGetterFunctions.put(
				"pageNumber", DocumentChunk::getPageNumber);
			attributeGetterFunctions.put(
				"embedding", DocumentChunk::getEmbedding);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<DocumentChunk, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<DocumentChunk, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<DocumentChunk, ?>>();

			attributeSetterBiConsumers.put(
				"chunkId",
				(BiConsumer<DocumentChunk, Long>)DocumentChunk::setChunkId);
			attributeSetterBiConsumers.put(
				"documentId",
				(BiConsumer<DocumentChunk, Long>)DocumentChunk::setDocumentId);
			attributeSetterBiConsumers.put(
				"chunkText",
				(BiConsumer<DocumentChunk, String>)DocumentChunk::setChunkText);
			attributeSetterBiConsumers.put(
				"pageNumber",
				(BiConsumer<DocumentChunk, Integer>)
					DocumentChunk::setPageNumber);
			attributeSetterBiConsumers.put(
				"embedding",
				(BiConsumer<DocumentChunk, String>)DocumentChunk::setEmbedding);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getChunkId() {
		return _chunkId;
	}

	@Override
	public void setChunkId(long chunkId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_chunkId = chunkId;
	}

	@Override
	public long getDocumentId() {
		return _documentId;
	}

	@Override
	public void setDocumentId(long documentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentId = documentId;
	}

	@Override
	public String getChunkText() {
		if (_chunkText == null) {
			return "";
		}
		else {
			return _chunkText;
		}
	}

	@Override
	public void setChunkText(String chunkText) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_chunkText = chunkText;
	}

	@Override
	public int getPageNumber() {
		return _pageNumber;
	}

	@Override
	public void setPageNumber(int pageNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pageNumber = pageNumber;
	}

	@Override
	public String getEmbedding() {
		if (_embedding == null) {
			return "";
		}
		else {
			return _embedding;
		}
	}

	@Override
	public void setEmbedding(String embedding) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_embedding = embedding;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, DocumentChunk.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DocumentChunk toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DocumentChunk>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DocumentChunkImpl documentChunkImpl = new DocumentChunkImpl();

		documentChunkImpl.setChunkId(getChunkId());
		documentChunkImpl.setDocumentId(getDocumentId());
		documentChunkImpl.setChunkText(getChunkText());
		documentChunkImpl.setPageNumber(getPageNumber());
		documentChunkImpl.setEmbedding(getEmbedding());

		documentChunkImpl.resetOriginalValues();

		return documentChunkImpl;
	}

	@Override
	public DocumentChunk cloneWithOriginalValues() {
		DocumentChunkImpl documentChunkImpl = new DocumentChunkImpl();

		documentChunkImpl.setChunkId(
			this.<Long>getColumnOriginalValue("chunkId"));
		documentChunkImpl.setDocumentId(
			this.<Long>getColumnOriginalValue("documentId"));
		documentChunkImpl.setChunkText(
			this.<String>getColumnOriginalValue("chunkText"));
		documentChunkImpl.setPageNumber(
			this.<Integer>getColumnOriginalValue("pageNumber"));
		documentChunkImpl.setEmbedding(
			this.<String>getColumnOriginalValue("embedding"));

		return documentChunkImpl;
	}

	@Override
	public int compareTo(DocumentChunk documentChunk) {
		long primaryKey = documentChunk.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DocumentChunk)) {
			return false;
		}

		DocumentChunk documentChunk = (DocumentChunk)object;

		long primaryKey = documentChunk.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DocumentChunk> toCacheModel() {
		DocumentChunkCacheModel documentChunkCacheModel =
			new DocumentChunkCacheModel();

		documentChunkCacheModel.chunkId = getChunkId();

		documentChunkCacheModel.documentId = getDocumentId();

		documentChunkCacheModel.chunkText = getChunkText();

		String chunkText = documentChunkCacheModel.chunkText;

		if ((chunkText != null) && (chunkText.length() == 0)) {
			documentChunkCacheModel.chunkText = null;
		}

		documentChunkCacheModel.pageNumber = getPageNumber();

		documentChunkCacheModel.embedding = getEmbedding();

		String embedding = documentChunkCacheModel.embedding;

		if ((embedding != null) && (embedding.length() == 0)) {
			documentChunkCacheModel.embedding = null;
		}

		return documentChunkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DocumentChunk, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DocumentChunk, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DocumentChunk, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DocumentChunk)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DocumentChunk>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DocumentChunk.class, ModelWrapper.class);

	}

	private long _chunkId;
	private long _documentId;
	private String _chunkText;
	private int _pageNumber;
	private String _embedding;

	public <T> T getColumnValue(String columnName) {
		Function<DocumentChunk, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DocumentChunk)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("chunkId", _chunkId);
		_columnOriginalValues.put("documentId", _documentId);
		_columnOriginalValues.put("chunkText", _chunkText);
		_columnOriginalValues.put("pageNumber", _pageNumber);
		_columnOriginalValues.put("embedding", _embedding);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("chunkId", 1L);

		columnBitmasks.put("documentId", 2L);

		columnBitmasks.put("chunkText", 4L);

		columnBitmasks.put("pageNumber", 8L);

		columnBitmasks.put("embedding", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DocumentChunk _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:519249210