/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package ai.assistance.service.model.impl;

import ai.assistance.service.model.DocumentChunk;
import ai.assistance.service.service.DocumentChunkLocalServiceUtil;

/**
 * The extended model base implementation for the DocumentChunk service. Represents a row in the &quot;AI_DocumentChunk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DocumentChunkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DocumentChunkImpl
 * @see DocumentChunk
 * @generated
 */
public abstract class DocumentChunkBaseImpl
	extends DocumentChunkModelImpl implements DocumentChunk {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a document chunk model instance should use the <code>DocumentChunk</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DocumentChunkLocalServiceUtil.addDocumentChunk(this);
		}
		else {
			DocumentChunkLocalServiceUtil.updateDocumentChunk(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1156433491