/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hrms.attendance.model.impl;

import com.hrms.attendance.model.Attendance;
import com.hrms.attendance.model.AttendanceModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Attendance service. Represents a row in the &quot;HRMS_Attendance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AttendanceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AttendanceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AttendanceImpl
 * @generated
 */
@JSON(strict = true)
public class AttendanceModelImpl
	extends BaseModelImpl<Attendance> implements AttendanceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a attendance model instance should use the <code>Attendance</code> interface instead.
	 */
	public static final String TABLE_NAME = "HRMS_Attendance";

	public static final Object[][] TABLE_COLUMNS = {
		{"attendanceId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"employeeId", Types.BIGINT}, {"attendanceDate", Types.TIMESTAMP},
		{"checkInTime", Types.TIMESTAMP}, {"checkOutTime", Types.TIMESTAMP},
		{"checkInIP", Types.VARCHAR}, {"checkOutIP", Types.VARCHAR},
		{"checkInLatitude", Types.DOUBLE}, {"checkInLongitude", Types.DOUBLE},
		{"checkOutLatitude", Types.DOUBLE}, {"checkOutLongitude", Types.DOUBLE},
		{"status", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("attendanceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("attendanceDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("checkInTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("checkOutTime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("checkInIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("checkOutIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("checkInLatitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("checkInLongitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("checkOutLatitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("checkOutLongitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table HRMS_Attendance (attendanceId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,employeeId LONG,attendanceDate DATE null,checkInTime DATE null,checkOutTime DATE null,checkInIP VARCHAR(75) null,checkOutIP VARCHAR(75) null,checkInLatitude DOUBLE,checkInLongitude DOUBLE,checkOutLatitude DOUBLE,checkOutLongitude DOUBLE,status VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table HRMS_Attendance";

	public static final String ORDER_BY_JPQL =
		" ORDER BY attendance.attendanceId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY HRMS_Attendance.attendanceId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ATTENDANCEDATE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ATTENDANCEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AttendanceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _attendanceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAttendanceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _attendanceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Attendance.class;
	}

	@Override
	public String getModelClassName() {
		return Attendance.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Attendance, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Attendance, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Attendance, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Attendance)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Attendance, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Attendance, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Attendance)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Attendance, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Attendance, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Attendance, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Attendance, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Attendance, Object>>();

			attributeGetterFunctions.put(
				"attendanceId", Attendance::getAttendanceId);
			attributeGetterFunctions.put("groupId", Attendance::getGroupId);
			attributeGetterFunctions.put("companyId", Attendance::getCompanyId);
			attributeGetterFunctions.put("userId", Attendance::getUserId);
			attributeGetterFunctions.put(
				"createDate", Attendance::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Attendance::getModifiedDate);
			attributeGetterFunctions.put(
				"employeeId", Attendance::getEmployeeId);
			attributeGetterFunctions.put(
				"attendanceDate", Attendance::getAttendanceDate);
			attributeGetterFunctions.put(
				"checkInTime", Attendance::getCheckInTime);
			attributeGetterFunctions.put(
				"checkOutTime", Attendance::getCheckOutTime);
			attributeGetterFunctions.put("checkInIP", Attendance::getCheckInIP);
			attributeGetterFunctions.put(
				"checkOutIP", Attendance::getCheckOutIP);
			attributeGetterFunctions.put(
				"checkInLatitude", Attendance::getCheckInLatitude);
			attributeGetterFunctions.put(
				"checkInLongitude", Attendance::getCheckInLongitude);
			attributeGetterFunctions.put(
				"checkOutLatitude", Attendance::getCheckOutLatitude);
			attributeGetterFunctions.put(
				"checkOutLongitude", Attendance::getCheckOutLongitude);
			attributeGetterFunctions.put("status", Attendance::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Attendance, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Attendance, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Attendance, ?>>();

			attributeSetterBiConsumers.put(
				"attendanceId",
				(BiConsumer<Attendance, Long>)Attendance::setAttendanceId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<Attendance, Long>)Attendance::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Attendance, Long>)Attendance::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Attendance, Long>)Attendance::setUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Attendance, Date>)Attendance::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Attendance, Date>)Attendance::setModifiedDate);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<Attendance, Long>)Attendance::setEmployeeId);
			attributeSetterBiConsumers.put(
				"attendanceDate",
				(BiConsumer<Attendance, Date>)Attendance::setAttendanceDate);
			attributeSetterBiConsumers.put(
				"checkInTime",
				(BiConsumer<Attendance, Date>)Attendance::setCheckInTime);
			attributeSetterBiConsumers.put(
				"checkOutTime",
				(BiConsumer<Attendance, Date>)Attendance::setCheckOutTime);
			attributeSetterBiConsumers.put(
				"checkInIP",
				(BiConsumer<Attendance, String>)Attendance::setCheckInIP);
			attributeSetterBiConsumers.put(
				"checkOutIP",
				(BiConsumer<Attendance, String>)Attendance::setCheckOutIP);
			attributeSetterBiConsumers.put(
				"checkInLatitude",
				(BiConsumer<Attendance, Double>)Attendance::setCheckInLatitude);
			attributeSetterBiConsumers.put(
				"checkInLongitude",
				(BiConsumer<Attendance, Double>)
					Attendance::setCheckInLongitude);
			attributeSetterBiConsumers.put(
				"checkOutLatitude",
				(BiConsumer<Attendance, Double>)
					Attendance::setCheckOutLatitude);
			attributeSetterBiConsumers.put(
				"checkOutLongitude",
				(BiConsumer<Attendance, Double>)
					Attendance::setCheckOutLongitude);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<Attendance, String>)Attendance::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getAttendanceId() {
		return _attendanceId;
	}

	@Override
	public void setAttendanceId(long attendanceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_attendanceId = attendanceId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@JSON
	@Override
	public Date getAttendanceDate() {
		return _attendanceDate;
	}

	@Override
	public void setAttendanceDate(Date attendanceDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_attendanceDate = attendanceDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalAttendanceDate() {
		return getColumnOriginalValue("attendanceDate");
	}

	@JSON
	@Override
	public Date getCheckInTime() {
		return _checkInTime;
	}

	@Override
	public void setCheckInTime(Date checkInTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_checkInTime = checkInTime;
	}

	@JSON
	@Override
	public Date getCheckOutTime() {
		return _checkOutTime;
	}

	@Override
	public void setCheckOutTime(Date checkOutTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_checkOutTime = checkOutTime;
	}

	@JSON
	@Override
	public String getCheckInIP() {
		if (_checkInIP == null) {
			return "";
		}
		else {
			return _checkInIP;
		}
	}

	@Override
	public void setCheckInIP(String checkInIP) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_checkInIP = checkInIP;
	}

	@JSON
	@Override
	public String getCheckOutIP() {
		if (_checkOutIP == null) {
			return "";
		}
		else {
			return _checkOutIP;
		}
	}

	@Override
	public void setCheckOutIP(String checkOutIP) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_checkOutIP = checkOutIP;
	}

	@JSON
	@Override
	public double getCheckInLatitude() {
		return _checkInLatitude;
	}

	@Override
	public void setCheckInLatitude(double checkInLatitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_checkInLatitude = checkInLatitude;
	}

	@JSON
	@Override
	public double getCheckInLongitude() {
		return _checkInLongitude;
	}

	@Override
	public void setCheckInLongitude(double checkInLongitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_checkInLongitude = checkInLongitude;
	}

	@JSON
	@Override
	public double getCheckOutLatitude() {
		return _checkOutLatitude;
	}

	@Override
	public void setCheckOutLatitude(double checkOutLatitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_checkOutLatitude = checkOutLatitude;
	}

	@JSON
	@Override
	public double getCheckOutLongitude() {
		return _checkOutLongitude;
	}

	@Override
	public void setCheckOutLongitude(double checkOutLongitude) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_checkOutLongitude = checkOutLongitude;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Attendance.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Attendance toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Attendance>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AttendanceImpl attendanceImpl = new AttendanceImpl();

		attendanceImpl.setAttendanceId(getAttendanceId());
		attendanceImpl.setGroupId(getGroupId());
		attendanceImpl.setCompanyId(getCompanyId());
		attendanceImpl.setUserId(getUserId());
		attendanceImpl.setCreateDate(getCreateDate());
		attendanceImpl.setModifiedDate(getModifiedDate());
		attendanceImpl.setEmployeeId(getEmployeeId());
		attendanceImpl.setAttendanceDate(getAttendanceDate());
		attendanceImpl.setCheckInTime(getCheckInTime());
		attendanceImpl.setCheckOutTime(getCheckOutTime());
		attendanceImpl.setCheckInIP(getCheckInIP());
		attendanceImpl.setCheckOutIP(getCheckOutIP());
		attendanceImpl.setCheckInLatitude(getCheckInLatitude());
		attendanceImpl.setCheckInLongitude(getCheckInLongitude());
		attendanceImpl.setCheckOutLatitude(getCheckOutLatitude());
		attendanceImpl.setCheckOutLongitude(getCheckOutLongitude());
		attendanceImpl.setStatus(getStatus());

		attendanceImpl.resetOriginalValues();

		return attendanceImpl;
	}

	@Override
	public Attendance cloneWithOriginalValues() {
		AttendanceImpl attendanceImpl = new AttendanceImpl();

		attendanceImpl.setAttendanceId(
			this.<Long>getColumnOriginalValue("attendanceId"));
		attendanceImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		attendanceImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		attendanceImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		attendanceImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		attendanceImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		attendanceImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		attendanceImpl.setAttendanceDate(
			this.<Date>getColumnOriginalValue("attendanceDate"));
		attendanceImpl.setCheckInTime(
			this.<Date>getColumnOriginalValue("checkInTime"));
		attendanceImpl.setCheckOutTime(
			this.<Date>getColumnOriginalValue("checkOutTime"));
		attendanceImpl.setCheckInIP(
			this.<String>getColumnOriginalValue("checkInIP"));
		attendanceImpl.setCheckOutIP(
			this.<String>getColumnOriginalValue("checkOutIP"));
		attendanceImpl.setCheckInLatitude(
			this.<Double>getColumnOriginalValue("checkInLatitude"));
		attendanceImpl.setCheckInLongitude(
			this.<Double>getColumnOriginalValue("checkInLongitude"));
		attendanceImpl.setCheckOutLatitude(
			this.<Double>getColumnOriginalValue("checkOutLatitude"));
		attendanceImpl.setCheckOutLongitude(
			this.<Double>getColumnOriginalValue("checkOutLongitude"));
		attendanceImpl.setStatus(this.<String>getColumnOriginalValue("status"));

		return attendanceImpl;
	}

	@Override
	public int compareTo(Attendance attendance) {
		long primaryKey = attendance.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Attendance)) {
			return false;
		}

		Attendance attendance = (Attendance)object;

		long primaryKey = attendance.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Attendance> toCacheModel() {
		AttendanceCacheModel attendanceCacheModel = new AttendanceCacheModel();

		attendanceCacheModel.attendanceId = getAttendanceId();

		attendanceCacheModel.groupId = getGroupId();

		attendanceCacheModel.companyId = getCompanyId();

		attendanceCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			attendanceCacheModel.createDate = createDate.getTime();
		}
		else {
			attendanceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			attendanceCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			attendanceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		attendanceCacheModel.employeeId = getEmployeeId();

		Date attendanceDate = getAttendanceDate();

		if (attendanceDate != null) {
			attendanceCacheModel.attendanceDate = attendanceDate.getTime();
		}
		else {
			attendanceCacheModel.attendanceDate = Long.MIN_VALUE;
		}

		Date checkInTime = getCheckInTime();

		if (checkInTime != null) {
			attendanceCacheModel.checkInTime = checkInTime.getTime();
		}
		else {
			attendanceCacheModel.checkInTime = Long.MIN_VALUE;
		}

		Date checkOutTime = getCheckOutTime();

		if (checkOutTime != null) {
			attendanceCacheModel.checkOutTime = checkOutTime.getTime();
		}
		else {
			attendanceCacheModel.checkOutTime = Long.MIN_VALUE;
		}

		attendanceCacheModel.checkInIP = getCheckInIP();

		String checkInIP = attendanceCacheModel.checkInIP;

		if ((checkInIP != null) && (checkInIP.length() == 0)) {
			attendanceCacheModel.checkInIP = null;
		}

		attendanceCacheModel.checkOutIP = getCheckOutIP();

		String checkOutIP = attendanceCacheModel.checkOutIP;

		if ((checkOutIP != null) && (checkOutIP.length() == 0)) {
			attendanceCacheModel.checkOutIP = null;
		}

		attendanceCacheModel.checkInLatitude = getCheckInLatitude();

		attendanceCacheModel.checkInLongitude = getCheckInLongitude();

		attendanceCacheModel.checkOutLatitude = getCheckOutLatitude();

		attendanceCacheModel.checkOutLongitude = getCheckOutLongitude();

		attendanceCacheModel.status = getStatus();

		String status = attendanceCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			attendanceCacheModel.status = null;
		}

		return attendanceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Attendance, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Attendance, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Attendance, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Attendance)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Attendance>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Attendance.class, ModelWrapper.class);

	}

	private long _attendanceId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _employeeId;
	private Date _attendanceDate;
	private Date _checkInTime;
	private Date _checkOutTime;
	private String _checkInIP;
	private String _checkOutIP;
	private double _checkInLatitude;
	private double _checkInLongitude;
	private double _checkOutLatitude;
	private double _checkOutLongitude;
	private String _status;

	public <T> T getColumnValue(String columnName) {
		Function<Attendance, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Attendance)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("attendanceId", _attendanceId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("attendanceDate", _attendanceDate);
		_columnOriginalValues.put("checkInTime", _checkInTime);
		_columnOriginalValues.put("checkOutTime", _checkOutTime);
		_columnOriginalValues.put("checkInIP", _checkInIP);
		_columnOriginalValues.put("checkOutIP", _checkOutIP);
		_columnOriginalValues.put("checkInLatitude", _checkInLatitude);
		_columnOriginalValues.put("checkInLongitude", _checkInLongitude);
		_columnOriginalValues.put("checkOutLatitude", _checkOutLatitude);
		_columnOriginalValues.put("checkOutLongitude", _checkOutLongitude);
		_columnOriginalValues.put("status", _status);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("attendanceId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("employeeId", 64L);

		columnBitmasks.put("attendanceDate", 128L);

		columnBitmasks.put("checkInTime", 256L);

		columnBitmasks.put("checkOutTime", 512L);

		columnBitmasks.put("checkInIP", 1024L);

		columnBitmasks.put("checkOutIP", 2048L);

		columnBitmasks.put("checkInLatitude", 4096L);

		columnBitmasks.put("checkInLongitude", 8192L);

		columnBitmasks.put("checkOutLatitude", 16384L);

		columnBitmasks.put("checkOutLongitude", 32768L);

		columnBitmasks.put("status", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Attendance _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1038530848