/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hrms.attendance.model.impl;

import com.hrms.attendance.model.Attendance;
import com.hrms.attendance.service.AttendanceLocalServiceUtil;

/**
 * The extended model base implementation for the Attendance service. Represents a row in the &quot;HRMS_Attendance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AttendanceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AttendanceImpl
 * @see Attendance
 * @generated
 */
public abstract class AttendanceBaseImpl
	extends AttendanceModelImpl implements Attendance {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a attendance model instance should use the <code>Attendance</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AttendanceLocalServiceUtil.addAttendance(this);
		}
		else {
			AttendanceLocalServiceUtil.updateAttendance(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1134474161