/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hrms.employee.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Department service. Represents a row in the &quot;HRMS_Department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hrms.employee.model.impl.DepartmentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hrms.employee.model.impl.DepartmentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Department
 * @generated
 */
@ProviderType
public interface DepartmentModel
	extends BaseModel<Department>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a department model instance should use the {@link Department} interface instead.
	 */

	/**
	 * Returns the primary key of this department.
	 *
	 * @return the primary key of this department
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this department.
	 *
	 * @param primaryKey the primary key of this department
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the department ID of this department.
	 *
	 * @return the department ID of this department
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this department.
	 *
	 * @param departmentId the department ID of this department
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the department code of this department.
	 *
	 * @return the department code of this department
	 */
	@AutoEscape
	public String getDepartmentCode();

	/**
	 * Sets the department code of this department.
	 *
	 * @param departmentCode the department code of this department
	 */
	public void setDepartmentCode(String departmentCode);

	/**
	 * Returns the department name of this department.
	 *
	 * @return the department name of this department
	 */
	@AutoEscape
	public String getDepartmentName();

	/**
	 * Sets the department name of this department.
	 *
	 * @param departmentName the department name of this department
	 */
	public void setDepartmentName(String departmentName);

	/**
	 * Returns the description of this department.
	 *
	 * @return the description of this department
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this department.
	 *
	 * @param description the description of this department
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this department.
	 *
	 * @return the status of this department
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this department.
	 *
	 * @param status the status of this department
	 */
	public void setStatus(String status);

	/**
	 * Returns the group ID of this department.
	 *
	 * @return the group ID of this department
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this department.
	 *
	 * @param groupId the group ID of this department
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this department.
	 *
	 * @return the company ID of this department
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this department.
	 *
	 * @param companyId the company ID of this department
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this department.
	 *
	 * @return the user ID of this department
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this department.
	 *
	 * @param userId the user ID of this department
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this department.
	 *
	 * @return the user uuid of this department
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this department.
	 *
	 * @param userUuid the user uuid of this department
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this department.
	 *
	 * @return the user name of this department
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this department.
	 *
	 * @param userName the user name of this department
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this department.
	 *
	 * @return the create date of this department
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this department.
	 *
	 * @param createDate the create date of this department
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this department.
	 *
	 * @return the modified date of this department
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this department.
	 *
	 * @param modifiedDate the modified date of this department
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Department cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1708583386