/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.hrms.employee.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Designation service. Represents a row in the &quot;HRMS_Designation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.hrms.employee.model.impl.DesignationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.hrms.employee.model.impl.DesignationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Designation
 * @generated
 */
@ProviderType
public interface DesignationModel
	extends BaseModel<Designation>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a designation model instance should use the {@link Designation} interface instead.
	 */

	/**
	 * Returns the primary key of this designation.
	 *
	 * @return the primary key of this designation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this designation.
	 *
	 * @param primaryKey the primary key of this designation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the designation ID of this designation.
	 *
	 * @return the designation ID of this designation
	 */
	public long getDesignationId();

	/**
	 * Sets the designation ID of this designation.
	 *
	 * @param designationId the designation ID of this designation
	 */
	public void setDesignationId(long designationId);

	/**
	 * Returns the designation code of this designation.
	 *
	 * @return the designation code of this designation
	 */
	@AutoEscape
	public String getDesignationCode();

	/**
	 * Sets the designation code of this designation.
	 *
	 * @param designationCode the designation code of this designation
	 */
	public void setDesignationCode(String designationCode);

	/**
	 * Returns the designation name of this designation.
	 *
	 * @return the designation name of this designation
	 */
	@AutoEscape
	public String getDesignationName();

	/**
	 * Sets the designation name of this designation.
	 *
	 * @param designationName the designation name of this designation
	 */
	public void setDesignationName(String designationName);

	/**
	 * Returns the description of this designation.
	 *
	 * @return the description of this designation
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this designation.
	 *
	 * @param description the description of this designation
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this designation.
	 *
	 * @return the status of this designation
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this designation.
	 *
	 * @param status the status of this designation
	 */
	public void setStatus(String status);

	/**
	 * Returns the group ID of this designation.
	 *
	 * @return the group ID of this designation
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this designation.
	 *
	 * @param groupId the group ID of this designation
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this designation.
	 *
	 * @return the company ID of this designation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this designation.
	 *
	 * @param companyId the company ID of this designation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this designation.
	 *
	 * @return the user ID of this designation
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this designation.
	 *
	 * @param userId the user ID of this designation
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this designation.
	 *
	 * @return the user uuid of this designation
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this designation.
	 *
	 * @param userUuid the user uuid of this designation
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this designation.
	 *
	 * @return the user name of this designation
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this designation.
	 *
	 * @param userName the user name of this designation
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this designation.
	 *
	 * @return the create date of this designation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this designation.
	 *
	 * @param createDate the create date of this designation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this designation.
	 *
	 * @return the modified date of this designation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this designation.
	 *
	 * @param modifiedDate the modified date of this designation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Designation cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:787884034